const ART = [
  {"title": "Owl",
   "filename": "owl.txt",
   "credit_text": "Donovan Bake",
   "credit_url": "https://www.asciiart.eu/animals/birds-land"},
  {"title": "Earth",
   "filename": "earth.txt",
   "credit_text": "jgs",
   "credit_url": "https://www.asciiart.eu/space/planets"},
  {"title": "Capitals Logo",
   "filename": "capitals.txt",
   "credit_text": "Brian Odom",
   "credit_url": "https://www.asciiart.eu/sports-and-outdoors/ice-hockey"},
  {"title": "Satellite",
   "filename": "Satellite.txt",
   "credit_text": "anonymous",
   "credit_url": "https://www.asciiart.eu/space/satellites"},
  {"title": "X-Wing",
   "filename": "x-wing.txt",
   "credit_text": "Shanaka Dias",
   "credit_url": "https://www.asciiart.eu/movies/star-wars"},
];
