const ART = [
  {"title": "Owl",
   "filename": "owl.txt",
   "credit_text": "Donovan Bake",
   "credit_url": "https://www.asciiart.eu/animals/birds-land"},
  {"title": "Earth",
   "filename": "earth.txt",
   "credit_text": "jgs",
   "credit_url": "https://www.asciiart.eu/space/planets"},
  {"title": "Satellite",
   "filename": "Satellite.txt",
   "credit_text": "anonymous",
   "credit_url": "https://www.asciiart.eu/space/satellites"},
  {"title": "Mogus",
   "filename": "mogus.txt",
   "credit_text": "Anonymous",
   "credit_url": "https://www.twitchquotes.com/copypastas/3822"},
];
