const ART = [
  {"title": "Owl",
   "filename": "owl.txt",
   "credit_text": "Donovan Bake",
   "credit_url": "https://www.asciiart.eu/animals/birds-land"},
  {"title": "Earth",
   "filename": "earth.txt",
   "credit_text": "jgs",
   "credit_url": "https://www.asciiart.eu/space/planets"},
   {"title": "Sonic",
   "filename": "Sonic.txt",
   "credit_text": "Han J. Lee",
   "credit_url": "https://www.asciiart.eu/video-games/sonic-the-hedgehog"},
  {"title": "Razza - a mix of Lab and Chow",
   "filename": "dog.txt",
   "credit_text": "anonymous",
   "credit_url": "https://www.asciiart.eu/animals/dogs"},
  {"title": "Cactus",
   "filename": "cactus.txt",
   "credit_text": "kra",
   "credit_url": "https://www.asciiart.eu/plants/cactus"},
  {"title": "Frogs",
   "filename": "frogs.txt",
   "credit_text": "VK",
   "credit_url": "https://www.asciiart.eu/animals/frogs"},
  {"title": "Capitals Logo",
   "filename": "capitals.txt",
   "credit_text": "Brian Odom",
   "credit_url": "https://www.asciiart.eu/sports-and-outdoors/ice-hockey"},
  {"title": "Satellite",
   "filename": "Satellite.txt",
   "credit_text": "anonymous",
   "credit_url": "https://www.asciiart.eu/space/satellites"},
  {"title": "X-Wing",
   "filename": "x-wing.txt",
   "credit_text": "Shanaka Dias",
   "credit_url": "https://www.asciiart.eu/movies/star-wars"},
];
